[package]
name = "datalogging_thermometer_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.17"  # eframe for GUI
serialport = "4.1"  # For serial communication
tokio = { version = "1", features = ["full"] }  # For async tasks and serial reading
